
With Customer_stg As
(
SELECT CU.CUSTOMER_ID,CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME) CUSTOMER_NAME,CN.EMAIL,CN.PHONE,
CU.NAME AS COMPANY_NAME ,ADDRESS,WEBSITE,CREDIT_LIMIT
FROM dbt-training-469915.ABC_Company.tbl_Contacts CN
INNER JOIN dbt-training-469915.ABC_Company.tbl_Customers CU
ON CU.CUSTOMER_ID =CN.CUSTOMER_ID
ORDER BY CUSTOMER_ID
)

Select * From Customer_stg
