
SELECT 
ROW_NUMBER() OVER (PARTITION BY od.ORDER_ID,ORDER_DATE,od.CUSTOMER_ID,CATEGORY_NAME ORDER BY od.ORDER_ID) AS RN,
od.ORDER_ID,ORDER_DATE,od.CUSTOMER_ID,STATUS,
ITEM_ID,ot.PRODUCT_ID,QUANTITY,UNIT_PRICE,PHONE,
CATEGORY_NAME,
COALESCE((QUANTITY*UNIT_PRICE),0) AS PRICE,
CASE WHEN ROW_NUMBER() OVER (PARTITION BY od.ORDER_ID,ORDER_DATE,od.CUSTOMER_ID,CATEGORY_NAME ORDER BY od.ORDER_ID)=1 THEN
COUNT(od.ORDER_ID) OVER (PARTITION BY od.ORDER_ID,ORDER_DATE,od.CUSTOMER_ID,CATEGORY_NAME ORDER BY od.ORDER_ID)
ELSE 0 END  AS ORDER_CNT_PER_CATEGORY,
COUNT(od.ORDER_ID) OVER (PARTITION BY od.ORDER_ID,ORDER_DATE,od.CUSTOMER_ID ORDER BY od.ORDER_ID) AS ORDER_CNT,
CASE WHEN ROW_NUMBER() OVER (PARTITION BY od.ORDER_ID,ORDER_DATE,od.CUSTOMER_ID,CATEGORY_NAME ORDER BY od.ORDER_ID)=1 THEN
SUM(COALESCE((QUANTITY*UNIT_PRICE),0)) OVER (PARTITION BY od.ORDER_ID,ORDER_DATE,od.CUSTOMER_ID,CATEGORY_NAME ORDER BY od.ORDER_ID) 
ELSE 0 END AS ORDER_AMOUNT_PER_CATEGORY,
SUM(COALESCE((QUANTITY*UNIT_PRICE),0)) OVER (PARTITION BY od.ORDER_ID,ORDER_DATE,od.CUSTOMER_ID ORDER BY od.ORDER_ID) AS ORDER_AMOUNT
from dbt-training-469915.ABC_Company.tbl_Orders od
INNER JOIN
dbt-training-469915.ABC_Company.tbl_OrderItems ot ON ot.ORDER_ID=od.ORDER_ID
INNER JOIN {{ref("stg_Customer_detail")}} cd ON cd.CUSTOMER_ID=od.CUSTOMER_ID
INNER JOIN{{ref("stg_Product_detail")}} pd ON pd.PRODUCT_ID=ot.PRODUCT_ID
GROUP BY 
od.ORDER_ID,ORDER_DATE,od.CUSTOMER_ID,STATUS,
ITEM_ID,ot.PRODUCT_ID,QUANTITY,UNIT_PRICE,PHONE,
CATEGORY_NAME
